# Generated by Django 3.2.8 on 2024-01-05 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test3',
        ),
    ]
