# Generated by Django 3.2.8 on 2024-01-05 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0002_delete_test3'),
    ]

    operations = [
        migrations.AddField(
            model_name='music_user',
            name='musername',
            field=models.TextField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=20),
        ),
    ]
