# Generated by Django 3.2.8 on 2024-01-05 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0004_alter_music_user_musername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music_user',
            old_name='musername',
            new_name='name',
        ),
    ]
