# Generated by Django 3.2.8 on 2024-01-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0005_rename_musername_music_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music_user',
            name='name',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
