# Generated by Django 3.2.8 on 2024-02-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0006_alter_music_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(default='未知歌曲', max_length=500, null=True)),
                ('music_image', models.URLField(default='/test/', null=True)),
                ('music_total_time', models.IntegerField()),
                ('music_creater', models.CharField(default='未知创作家', max_length=200, null=True)),
                ('music_upload_user_id', models.IntegerField()),
                ('music_upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='music_user',
            name='info',
            field=models.TextField(default='该用户很懒，什么都没输入'),
        ),
    ]
