# Generated by Django 3.2.8 on 2024-02-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0009_alter_music_music_upload_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_lrc_path',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_total_time',
            field=models.FloatField(),
        ),
    ]
