# Generated by Django 3.2.8 on 2024-02-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0010_auto_20240226_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
