# Generated by Django 3.2.8 on 2024-02-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0011_music_music_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite_Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('music_id', models.IntegerField()),
            ],
        ),
    ]
