# Generated by Django 3.2.8 on 2024-03-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0012_favorite_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='music_level',
            field=models.IntegerField(default=1),
        ),
    ]
