# Generated by Django 3.2.8 on 2024-03-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0013_auto_20240304_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_info',
            field=models.TextField(blank=True, default='该歌曲暂未添加介绍', null=True),
        ),
    ]
