# Generated by Django 3.2.8 on 2024-03-06 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_web', '0016_auto_20240306_1641'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
